// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdy-dDRwd2dBKBbotor3AieXxlpKtU4iA',
    appId: '1:726493416572:android:3e90ce93f39aef95e8cdf9',
    messagingSenderId: '726493416572',
    projectId: 'chifaa-40a7c',
    databaseURL: 'https://chifaa-40a7c-default-rtdb.firebaseio.com',
    storageBucket: 'chifaa-40a7c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrCcCnu1MkuTvZvHWef5x54PqSo-ebe2A',
    appId: '1:726493416572:ios:87badd3302a72332e8cdf9',
    messagingSenderId: '726493416572',
    projectId: 'chifaa-40a7c',
    databaseURL: 'https://chifaa-40a7c-default-rtdb.firebaseio.com',
    storageBucket: 'chifaa-40a7c.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationMs',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-JR8YazeLFQ8mlnxfi7k4BH8VAuhHRE4',
    appId: '1:726493416572:web:dbd87a31669a2a9fe8cdf9',
    messagingSenderId: '726493416572',
    projectId: 'chifaa-40a7c',
    authDomain: 'chifaa-40a7c.firebaseapp.com',
    databaseURL: 'https://chifaa-40a7c-default-rtdb.firebaseio.com',
    storageBucket: 'chifaa-40a7c.firebasestorage.app',
  );

}